"""Stage-11 purchase-order drafts, immutable approvals and audit events."""

MIGRATION_9 = [
    """CREATE TABLE order_projects (
        id INTEGER PRIMARY KEY,
        snapshot_id INTEGER NOT NULL REFERENCES snapshots(id),
        supplier TEXT NOT NULL,
        source_replenishment_run_id INTEGER NOT NULL UNIQUE REFERENCES replenishment_runs(id),
        created_at_utc TEXT NOT NULL,
        dataset_json TEXT NOT NULL)""",
    """CREATE TABLE order_versions (
        id INTEGER PRIMARY KEY,
        project_id INTEGER NOT NULL REFERENCES order_projects(id),
        version_number INTEGER NOT NULL,
        parent_version_id INTEGER REFERENCES order_versions(id),
        status TEXT NOT NULL CHECK(status IN ('draft','review','approved')),
        created_at_utc TEXT NOT NULL,
        created_by TEXT NOT NULL,
        submitted_at_utc TEXT,
        approved_at_utc TEXT,
        responsible TEXT,
        approval_note TEXT,
        approval_snapshot_json TEXT,
        UNIQUE(project_id, version_number))""",
    """CREATE TABLE order_items (
        version_id INTEGER NOT NULL REFERENCES order_versions(id),
        line_id TEXT NOT NULL,
        sku TEXT NOT NULL,
        article TEXT,
        code_1c TEXT NOT NULL,
        name TEXT,
        suggested_quantity REAL,
        selected_quantity REAL NOT NULL CHECK(selected_quantity >= 0),
        purchase_unit TEXT,
        correction_reason TEXT,
        changed_by TEXT,
        changed_at_utc TEXT,
        source_payload_json TEXT NOT NULL,
        PRIMARY KEY(version_id, line_id),
        UNIQUE(version_id, sku))""",
    """CREATE TABLE order_events (
        id INTEGER PRIMARY KEY,
        version_id INTEGER NOT NULL REFERENCES order_versions(id),
        line_id TEXT,
        action TEXT NOT NULL,
        actor TEXT NOT NULL,
        reason TEXT,
        created_at_utc TEXT NOT NULL,
        payload_json TEXT NOT NULL)""",
    "CREATE INDEX order_versions_project ON order_versions(project_id, version_number)",
    "CREATE INDEX order_events_version ON order_events(version_id, id)",
]
